stages:
  - build
  - deploy

docker-build:
  stage: build
  only:
    - tags
  script:
    - TAG=$CI_PROJECT_NAME:$CI_COMMIT_TAG
    - echo $TAG
    - docker build . -t $TAG -t $CI_PROJECT_NAME:local --build-arg VER=$CI_COMMIT_TAG --build-arg SHA1=$CI_COMMIT_SHORT_SHA

docker-deploy:
  stage: deploy
  script:
    - TAG=$CI_PROJECT_NAME:$CI_COMMIT_TAG
    - sed -i "s/$CI_PROJECT_NAME:local/$TAG/" docker-compose.yml
    - docker-compose up -d
  only:
    - tags
  